#-!/bin/sh


#PBS -N SAP-Fc-p11

#PBS -lwalltime=10:00:00

#PBS -lselect=1:ncpus=32:mem=104gb



module load intel-suite

module load gromacs/2018.2

module load mpi




module load mpi/intel-2019

module load gcc/6.2.0

module load intel-suite/2017.6



#set OMP_NUM_THREADS=8

#export OMP_NUM_THREADS=8


#set OMP_NUM_MPI=6

#export OMP_NUM_MPI=6


cd $PBS_O_WORKDIR

rm -f fort* sasa*.dat sasa*.xvg frame*.ndx frame*.dat atom*.dat
echo "Beginning generating frames"
./gen-frame.sh  # Generate frames (.gro files) from a trajectory file. The .gro files will be used for sasa calculation and neighbor list generation. 
echo "All frames generated"

echo "Modifying frame.gro files"
./sed.sh # Modify the .gro files by deleting the headers and footers to generate input for sap.f

echo "Generating framewise file names"
./input-filename.sh # Generate files with a list of filenames used for framewise input/output.

echo "Generating atomwise file names"
./output-filename.sh # Generate files with a list of filenames used for atomwise input/output.

echo "Generating neighbour list"
gfortran sap.f -mcmodel=medium # Generate a framewise list of atoms within cutoff of each atom.
./a.out

gfortran sequence.f #Generates a file called ressize.dat with the columns : resid, resname and residue atom count
./a.out
echo "Residuewise atom count generated"

./lines.sh # Count the number of lines in each output file from sap.f.

echo "Generating index files"
gfortran gen-index.f -mcmodel=medium # Generate framewise index files for SASA calculation.
./a.out

./lines-tracefile.sh # Number of lines in the files generated for tracing the sasa output based on 

echo "Generating SASA input files"
gfortran gen-sasa-input.f #generate input file to pipe in to gmx sasa for each frame
./a.out

echo "Modifying index files"
./cat-index.sh # Modify the index files generated by gen-index.f by adding the Fab/Fc+Histidine buffer domain atom indices in a group at the top. (Needs a file called common.ndx with the atom indices of all the protein atoms Fab/Fc+Histidine buffer)

./sasa.sh # Script file calculates SASA for each frame 

echo "Modifying SASA output files"
./sed-sasa.sh # Modify the SASA outputs to make the format uniform to be read by the fortran codes to follow

echo "Seggregating data framewise"
gfortran seggregate-framewise.f -mcmodel=medium # Add the SASA data to the tracefiles
./a.out

echo "Seggregating data atomwise"
gfortran seggregate-atomwise-2.f -mcmodel=medium # Seggregate the information in the tracefile by atom index
./a.out

./lines-atomsfile.sh # Calculate the number of lines in the output generated by seggregate-atomwise.f

echo "Adding hydrophobicity, free SASA and residue information to output files"
gfortran modify-atomfiles.f #Generate files for each atom containing all data needed for SAP calculation. A file named hydrophobicity.dat needed as an input. This is a 3-column file containing residue_name, hydrophobicity (Black and Mould) and the sasa (Ala-X-Ala) trimer as the three columns.
./a.out

gfortran sap-residuewise.f #Generates residuewsise SAP (The final output to be used for coloring)
./a.out

echo "Residue wise SAP calculated"
rm -f fort* sasa*.dat sasa*.xvg frame*.ndx frame*.dat atom*.dat
echo "DONE!!! Phewww..."

